Add TeleopAutoScoreCommandGroup
frc2357/FRC-2023 pull request #132
Opened 2023-02-22 00:20 UTC by Tyson453

2023-02-22 01:56 UTC, NolanCampbell2357 requested changes
This is a good initial thought process of what we need to do. Good work, We will have to rework it to actually incorporate the robot pose (need to discuss with @legokid on what the network table topic will be). We will also have to add the creation of the trajectory commands so we can auto score on the entire community.

2023-02-22 01:56 UTC, NolanCampbell2357 commented on robotbase/src/main/java/com/team2357/frc2023/controls/SwerveDriveControls.java
> +        m_aButton.onTrue(new TeleopAutoScoreCommandGroup());
Let's use a trigger so the driver does not have to let go of the sticks.

2023-02-22 02:19 UTC, legokid commented on robotbase/src/main/java/com/team2357/frc2023/controls/SwerveDriveControls.java
> +        m_aButton.onTrue(new TeleopAutoScoreCommandGroup());
Here is what I would suggest for the json format to be passed via networktables
https://github.com/frc2357/FRC-2023/blob/add/wpilibpi-test/wpilibpi/apriltags_nt.json

2023-02-22 20:56 UTC, NolanCampbell2357 commented on robotbase/src/main/java/com/team2357/frc2023/controls/SwerveDriveControls.java
> +        m_aButton.onTrue(new TeleopAutoScoreCommandGroup());
Thanks, we'll make this work.

2023-02-24 00:59 UTC, NolanCampbell2357 approved these changes

2023-02-24 01:34 UTC, merged