Add auto balance command
frc2357/FRC-2023 pull request #16
Opened 2023-01-10 23:45 UTC by Tyson453

2023-01-11 00:14 UTC, NolanCampbell2357 commented
Make it a draft if it's in progress

2023-01-13 20:50 UTC, NolanCampbell2357 commented
@Tyson453 The rebase we did Yesterday was unsuccessful. We needed to do a `onto` rebase. I have fixed it. You will need to do a `git pull --rebase` to update your branch.

2023-01-24 22:16 UTC, NolanCampbell2357 requested changes

2023-01-24 22:16 UTC, NolanCampbell2357 commented on robotbase/src/main/java/com/team2357/frc2023/subsystems/SwerveDriveSubsystem.java
> +		// return (-2.5 <= getRoll() && getRoll() <= 2.5) && (-2.5 <= getPitch() && getPitch() <= 2.5);
Remove unused code

2023-01-24 22:16 UTC, NolanCampbell2357 commented on robotbase/src/main/java/com/team2357/frc2023/commands/AutoBalanceCommand.java
> +        // System.out.println("Yaw: " + m_yaw);
Remove unused code

2023-01-24 22:16 UTC, NolanCampbell2357 commented on robotbase/src/main/java/com/team2357/frc2023/commands/AutoBalanceCommand.java
> +        m_yaw = Math.abs(SwerveDriveSubsystem.getInstance().getYaw() % 360);
You can reduce wordiness by assigning a member variable like `m_swerve` to the swerve subsystem, and just refer to that variable.

2023-01-24 22:16 UTC, NolanCampbell2357 commented on robotbase/src/main/java/com/team2357/frc2023/commands/AutoBalanceCommand.java
> +        m_yaw = Math.abs(SwerveDriveSubsystem.getInstance().getYaw() % 360);
However, complex command logic should be moved to the subsystem. We want commands to have as little logic as possible, and do it in the subsystem instead.

2023-01-25 19:16 UTC, NolanCampbell2357 requested changes
Looks very good. Just a couple small things.

2023-01-25 19:16 UTC, NolanCampbell2357 commented on robotbase/src/main/java/com/team2357/frc2023/subsystems/SwerveDriveSubsystem.java
> +		error = Math.copySign(Constants.DRIVE.BALANCE_LEVEL_DEGREES + Math.abs(angle), angle);
I am on the fence about having these constants in subsystem. Usually, we want constants to be passed as arguments to functions, or to set them as configs on the subsystem. The swerve subsystem is a little unique in that we know we will reuse this code year to year, so I would be okay with having the constants used in this method only, just so it is easier to remove after the season. Then again, we intend to re-write this subsystem using our own swerve stuff anyway, so having configs might be better. Use your best judgement to decide.

2023-01-25 19:16 UTC, NolanCampbell2357 commented on robotbase/src/main/java/com/team2357/frc2023/commands/AutoBalanceCommand.java
> +
Even if the `isFinished` method always returns false, it is a good idea to override ride it, so it is visible.

2023-01-26 01:32 UTC, Tyson453 commented on robotbase/src/main/java/com/team2357/frc2023/subsystems/SwerveDriveSubsystem.java
> +		error = Math.copySign(Constants.DRIVE.BALANCE_LEVEL_DEGREES + Math.abs(angle), angle);
Should I just move the balancing back into the command and put the if statements for the direction into a util class? Then there wouldn't be too much logic in the AutoBalanceCommand and there wouldn't be code specific to this year only in the SwerveDriveSubsystem.

2023-01-27 00:05 UTC, NolanCampbell2357 approved these changes

2023-01-27 00:05 UTC, NolanCampbell2357 commented on robotbase/src/main/java/com/team2357/frc2023/subsystems/SwerveDriveSubsystem.java
> +		error = Math.copySign(Constants.DRIVE.BALANCE_LEVEL_DEGREES + Math.abs(angle), angle);
Let's just leave it for now

2023-01-27 00:54 UTC, merged