Add target april tag selection
frc2357/FRC-2023 pull request #178
Opened 2023-03-01 02:09 UTC by NolanCampbell2357

2023-03-02 01:23 UTC, Tyson453 requested changes

2023-03-02 01:23 UTC, Tyson453 commented on robotbase/src/main/java/com/team2357/frc2023/commands/auto/TranslateToTargetCommand.java
> +        m_aprilTagId = -1;
Use aprilTagId instead of -1

2023-03-02 23:36 UTC, NolanCampbell2357 commented on robotbase/src/main/java/com/team2357/frc2023/commands/auto/TranslateToTargetCommand.java
> +        m_aprilTagId = -1;
Good catch

2023-03-03 01:57 UTC, Tyson453 approved these changes

2023-03-03 02:30 UTC, merged