Update buttonboard topics on robotcode
frc2357/FRC-2023 pull request #232
Opened 2023-03-11 21:58 UTC by NolanCampbell2357

2023-03-12 02:06 UTC, Tyson453 requested changes

2023-03-12 02:06 UTC, Tyson453 commented on robotbase/src/main/java/com/team2357/frc2023/Constants.java
> +        public static final String INTAKE_EXTEND_TOPIC_NAME = "intakeExtend";
Can intakeSpeed and intakeExtend be renamed to intakeRoller and intakeSolenoid?

2023-03-12 15:47 UTC, NolanCampbell2357 commented on robotbase/src/main/java/com/team2357/frc2023/Constants.java
> +        public static final String INTAKE_EXTEND_TOPIC_NAME = "intakeExtend";
No, I did not choose these

2023-03-13 17:54 UTC, Tyson453 approved these changes

2023-03-14 20:04 UTC, merged