Panic mode arm rotation
frc2357/FRC-2023 pull request #83
Opened 2023-02-04 19:19 UTC by MidgleyM

2023-02-04 19:37 UTC, NolanCampbell2357 requested changes

2023-02-04 19:37 UTC, NolanCampbell2357 commented on robotbase/src/main/java/com/team2357/frc2023/commands/PanicModeArmExtender.java
> +package com.team2357.frc2023.commands;
delete this

2023-02-04 19:37 UTC, NolanCampbell2357 commented on robotbase/src/main/java/com/team2357/frc2023/controls/GunnerControls.java
>          aButton.onTrue(new WristToggleCommand());
I did not catch this previously. This bind should require the left dpad to be pressed as well.

2023-02-04 19:37 UTC, NolanCampbell2357 commented on robotbase/src/main/java/com/team2357/frc2023/controls/GunnerControls.java
>          aButton.onTrue(new WristToggleCommand());
Add a config for max speed when using controller axis

2023-02-04 19:37 UTC, NolanCampbell2357 commented on robotbase/src/main/java/com/team2357/frc2023/commands/human/panic/ArmRotationCommand.java
> +        ArmRotationSubsystem.getInstance().rotate(m_axis.getValue());
Subsystem method that you call should have a max speed you multiply the value you pass here by.

2023-02-04 21:15 UTC, NolanCampbell2357 requested changes

2023-02-04 21:15 UTC, NolanCampbell2357 commented on robotbase/src/main/java/com/team2357/frc2023/commands/human/panic/ArmRotationCommand.java
> +
Override isFinished and always return false. This is what happens behind the scenes, but we should have it explicitly in the command

2023-02-04 21:15 UTC, NolanCampbell2357 commented on robotbase/src/main/java/com/team2357/frc2023/commands/human/panic/ArmExtenderCommand.java
Override isFinished and always return false. This is what happens behind the scenes, but we should have it explicitly in the command

2023-02-07 01:04 UTC, NolanCampbell2357 requested changes

2023-02-07 01:04 UTC, NolanCampbell2357 commented on robotbase/src/main/java/com/team2357/frc2023/subsystems/ArmExtensionSubsystem.java
> +        m_config = Constants.ARM_EXTENSION.GET_EXTENSION_CONFIG();
We should never use constants within subsystems. The config should be set through the subsystem's creation in `SubsystemFactory`

2023-02-09 01:04 UTC, NolanCampbell2357 commented
You need to add a method to create an instance of the arm rotation subsystem to `SubsystemFactory`. That method should then be called in `RobotContainer`. If we ran this on the robot we would get a null pointer exception on the commands due to no instance of the subsystem existing.

2023-02-11 23:27 UTC, NolanCampbell2357 submitted a review, later dismissed

2023-02-11 23:27 UTC, NolanCampbell2357 commented on robotbase/src/main/java/com/team2357/frc2023/subsystems/SubsystemFactory.java
>          }
You need to instantiate the arm extension subsystem as well

2023-02-11 23:27 UTC, NolanCampbell2357 commented on robotbase/src/main/java/com/team2357/frc2023/subsystems/SubsystemFactory.java
>          }
I also do not see a call in `RobotContainer` to `SubsystemFactory` to create the arm rotation subsystem in

2023-02-14 21:41 UTC, Tyson453 approved these changes

2023-02-14 21:42 UTC, merged